VIA_ENABLE = yes
ENCODER_MAP_ENABLE = yes
MAXTOUCH_DEBUG = no

POINTING_DEVICE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
DILEMMA_MINIMUM_DEFAULT_DPI = 400
DILEMMA_DEFAULT_DPI_CONFIG_STEP = 200